### ISSUE TITLE
Generate stock assessment input data using EwE outputs

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [Bai-Li-NOAA/IFA4EBFM#2]
After discussion with Andrea, Chantel, Jim, and Nathan, we think the below functions could help generate single species stock assessment data using Ecopath with Ecosim (EwE) outputs:

- A function that creates one/multiple fleets using EwE catch_annual.csv. The function returns time series of observed catch and age composition data for each fleet.
- A function that creates multiple surveys using EwE biomss_annual.csv and biomass_monthly.csv). The function returns time series survey indices and age & length composition data.
- A function that summarizes biological data from EwE outputs
- A function that converts simulated fishery and survey data to single species stock assessment input data files (e.g., ewe2ss and ewe2jabba). 

To complete the functions:

- [ ] @jimianelli-NOAA, could you post links of R packages/functions that help with reading in EwE inputs/outputs if there are any? 
- [ ] @jimianelli-NOAA can help review create_fishery() function once it is posted online
- [x] @chantelwetzel-noaa, could you post links of functions/code that implement age errors and converts age comp to length comp in this issue?
- [x] @nathanvaughan-NOAA, could you post links of relevant SSMSE code that may help with generating stock assessment input data in this issue?
- [ ] @Andrea-Havron-NOAA, feel free to drop any thoughts on how to generate environmental data with errors in this issue. 

Thanks!

**Comment by nathanvaughan-NOAA** [comment]
Modifying SS input files to add new years of data.
The basic functionality to do this revolves around the R4SS functions to read and write the data and control files (and the parameter file and forecast file in some cases)
SS_readctl()  which is a wrapper for SS_readctl_3.30() 
SS_writectl()
SS_readdat() which is a wrapper for SS_readdat_3.30()
SS_writedat()
SS_readforecast()  
SS_writeforecast()
SS_readpar_3.30() 
SS_writepar_3.30()
All of these functions build large list objects representing all the possible inputs into the respective SS files. 
In SSMSE we update the files with both updated fishery data for each year of the simulation and with annual deviations on parameters to implement process error. We found that switching all parameters to time-varying using deviation vectors was the simplest way to facilitate a variety of user specified future parameter patterns with a universal approach. Below are links to some of the key function code we use for updating the operating model files. 
https://github.com/nmfs-fish-tools/SSMSE/blob/main/R/single_extend_OM.R
https://github.com/nmfs-fish-tools/SSMSE/blob/main/R/extendOM.R

**Comment by chantelwetzel-noaa** [comment]
Here is the Stock Synthesis technical description with the age-length transition matrix calculation shown in [equation A.1.14](https://sedarweb.org/docs/wsupp/S39_RD_08_Methot_and_Wetzel_2013_Fish_Res_App_A.pdf) and an example of how the age-length transition matrix can be calculated within R is shown between [lines 51-130](https://github.com/chantelwetzel-noaa/Chapter4_HCR/blob/master/functions/Get_Biology.R#L51).

**Comment by Bai-Li-NOAA** [comment]
Hi @jimianelli-NOAA, I pushed the [create_fishery() function](https://github.com/Bai-Li-NOAA/IFA4EBFM/blob/main/R/create_fishery.R) to the repo. If you have time to review the function, that would be great! You can also test the [sa_simulation.R script](https://github.com/Bai-Li-NOAA/IFA4EBFM/blob/main/Rscript/sa_simulation.R) to run create_fishery() after cloning the repo.  Feel free to submit an issue if you would like me to change anything or submit a pull request. Thanks!

**Comment by Bai-Li-NOAA** [comment]
create_fishery(), create_survey(), and create_biodata() can be used to simulate stock assessment input data. R code can be found [here](https://bai-li-noaa.github.io/IFA4EBFM/reference/index.html).
